print '
<!-- /Content -->
					</TD>
				</TR>				
			</TABLE>
		</TD>
		<TD BGCOLOR="#000000"><IMG SRC="images/p0.gif" 
		BORDER=0 WIDTH=1 HEIGHT=1 HSPACE=0 VSPACE=0></TD>
	</TR>
	<TR>
		<TD COLSPAN=3 BGCOLOR="#000000"><IMG 
		SRC="/images/p0.gif" BORDER=0 WIDTH=1 HEIGHT=1 
		HSPACE=0 VSPACE=0></TD>
	</TR>
	<TR><TD COLSPAN=4 BGCOLOR="#663300" VALIGN="TOP"><IMG 
	SRC="/images/pb.gif" BORDER=0 WIDTH=3 HEIGHT=1 HSPACE=0 
	VSPACE=0></TD></TR>
	<TR><TD COLSPAN=5 BGCOLOR="#996600" VALIGN="TOP"><IMG 
	SRC="/images/pb.gif" BORDER=0 WIDTH=4 HEIGHT=1 HSPACE=0 
	VSPACE=0></TD></TR>
	<TR><TD COLSPAN=6 BGCOLOR="#999900" VALIGN="TOP"><IMG 
	SRC="/images/pb.gif" BORDER=0 WIDTH=4 HEIGHT=1 HSPACE=0 
	VSPACE=0></TD></TR>
	<TR><TD COLSPAN=7 BGCOLOR="#CC9900" VALIGN="TOP"><IMG 
	SRC="/images/pb.gif" BORDER=0 WIDTH=5 HEIGHT=1 HSPACE=0 
	VSPACE=0></TD></TR>
	<TR>
		<TD COLSPAN=3 BGCOLOR="#FFCC00" ALIGN="CENTER" 
		VALIGN="TOP">&nbsp;</TD>
		<TD COLSPAN=4 BGCOLOR="#FFCC00"><IMG 
		SRC="/images/p.gif" BORDER=0 WIDTH=1 HEIGHT=1 
		HSPACE=0 VSPACE=0></TD>
	</TR>
</TABLE>
<div class="foot">created with nanoHttp</div>
</CENTER>
</BODY>
</HTML>
';
